project_id = "jjwfyiaddsznftszmxhc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://jjwfyiaddsznftszmxhc.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[db]
port = 54322

[functions.send-form-notifications]
verify_jwt = false

[functions.check-form-due-dates]
verify_jwt = false

[realtime]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324
image_transformation = {enabled = true}

[edge-runtime]
enabled = true
port = 54325

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"