// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjwfyiaddsznftszmxhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impqd2Z5aWFkZHN6bmZ0c3pteGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODUyMTcsImV4cCI6MjA2Njg2MTIxN30.tDZNGVclQg9TGPC0v8VXs8W2KJAjTtI35oNbY5pHDE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});